### ISSUE TITLE
Drop Reth DB providers as soon as possible

### ISSUE THREAD

**Issue by naps62** [ethui/indexer#18]
Instead of keeping a db provider around for every worker, we should drop them as soon as possible, otherwise we'll hit problems: https://github.com/paradigmxyz/reth/issues/5228

**Comment by ZePedroResende** [comment]
Tasks : 
  - Remove provider from struct , replace all places that break with explicit call to provider factory, make the provider drop the soonest possible. 
  - Remove RWLock from provider factory.
