### ISSUE TITLE
HTTP auth via address signature

### ISSUE THREAD

**Issue by ZePedroResende** [ethui/indexer#2]
This feature will provide authentication  for protected routes by leveraging Ethereum addresses and JWTs. 

This would work as follows:

- Initiate the authentication process: Client requests message and nonce from server

- Signing the Message: the user signs a message and nonce provided by the server using their Ethereum address. This involves creating a cryptographic signature of the message using their private key.

- Sending the Signature: The signed message is then sent to the server as part of the authentication request. It serves as proof that the user possesses the private key associated with the Ethereum address.

- Server Verification: Upon receiving the signed message, the server verifies the authenticity of the signature. It does so by extracting the Ethereum address from the signature and comparing it with the user's provided address.

- JWT Generation: If the signature is valid, the server generates a JSON Web Token (JWT) as a response.

- Use JWT for Protected Endpoints: The client receives the JWT token and includes it in the headers of subsequent requests to protected endpoints on the server. The server verifies the validity of the token, ensuring that the request is made by an authorised user.

**Comment by ZePedroResende** [comment]
One of the logical ways to implement JWT validation for requests in an actix-based application is by utilizing the [actix middleware system](https://actix.rs/docs/middleware/). I came across [a blogpost from auth0](https://auth0.com/blog/build-an-api-in-rust-with-jwt-authentication-using-actix-web/) that demonstrates how this can be achieved using actix middleware.

**Comment by naps62** [comment]
I think the nonce part can be simplified by using timestamps:

1. the user signs an EIP-712 message containing: `[address, current_timestmap, expiration_timestmap]`
2. sends the message, along with all 3 raw parameters
3. the server validates: 
  3.1 is the current_timestamp recent enough (e.g.: past 5 minutes)
  3.2 is the expiration_timestamp in the future?
  3.3 does the signature match the params, and is signed by the same address?
4. server emits a JWT with the given expiration

**Comment by ZePedroResende** [comment]
I agree, seems like a good idea 👍
